/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package exploregradle

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

class ExploreGradle {
    companion object {
        fun greeting(): String {
            return "Explore Gradle"
        }
    }
}
fun main() {
    println(App().greeting)
    println(ExploreGradle.greeting())
}
